@url = "http://localhost:3000/"
//get all flights
GET http://localhost:3000/user HTTP/1.1;
//get single flight based on ID
###
GET http://localhost:3000/user/6cf311e9-239e-44de-bf28-010fef35b588 HTTP/1.1;
// Add or book your flight
###
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    //"title": "flight to canada",
    //"price": "canada",
    "title": "flight to canada",
    "price": "26000",
    "password": "Zuriinternship"
}
// update/edit your flight details
###
PUT http://localhost:3000/user/005830a5-c74f-49e6-acf3-405ac5662683 HTTP/1.1
Content-Type: application/json

{
    //"title": "flight to canada",
    //"price": "canada",
    "title": "flight to USA",
    "price": "26000",
    "password": "ALX Software ENgineering"
}

// delete your flight details  based on ID
###
DELETE http://localhost:3000/user/b995c5da-60bb-4d21-a23e-2b45fb1de696 HTTP/1.1